import { jest } from '@jest/globals';
import User from '../models/user.js';
import jwt from 'jsonwebtoken';
import crypto from 'crypto';

describe('Algorithm Test: Cryptography & Security Tokens', () => {
  let userDoc;

  beforeAll(() => {
    // Inject mock environment variables so the algorithm works safely in a test environment
    process.env.JWT_SECRET = 'test_secret_key_123';
    process.env.JWT_EXPIRE = '30d';
  });

  beforeEach(() => {
    // Create an isolated user map in RAM
    userDoc = new User({
      _id: '507f1f77bcf86cd799439011',
      name: 'Crypto Test',
      email: 'crypto@test.com',
      password: 'hashed_password_mock',
    });
  });

  it('Step 1: Should correctly generate a mathematically valid JSON Web Token (JWT)', () => {
    const token = userDoc.getJwtToken();
    
    // JWT format mathematically always consists of 3 parts separated by dots (Header.Payload.Signature)
    expect(typeof token).toBe('string');
    expect(token.split('.').length).toBe(3);

    // Verify the algorithm cleanly digitally signs the package using the secret key
    const decoded = jwt.verify(token, process.env.JWT_SECRET);
    expect(decoded.id).toBe(userDoc._id.toString());
  });

  it('Step 2: Should safely generate and securely hash a password reset token (SHA-256)', () => {
    const rawResetToken = userDoc.getResetPasswordToken();

    // The raw intercept token should be standard entropy (20 random bytes = 40 hex characters)
    expect(rawResetToken).toHaveLength(40);

    // Security Verification: The document should NEVER store the raw token, only the hash!
    expect(userDoc.resetPasswordToken).not.toBe(rawResetToken);
    
    // A SHA-256 hash algorithm output must always be exactly 64 characters long
    expect(userDoc.resetPasswordToken).toHaveLength(64); 

    // The manually calculated SHA-256 hash mathematically MUST match the one generated by the controller
    const expectedHash = crypto.createHash('sha256').update(rawResetToken).digest('hex');
    expect(userDoc.resetPasswordToken).toBe(expectedHash);

    // Password reset windows should strictly be valid for exactly 10 minutes maximum before expiring
    const timeRemaining = userDoc.resetPasswordExpire.getTime() - Date.now();
    expect(timeRemaining).toBeGreaterThan(9 * 60 * 1000); 
    expect(timeRemaining).toBeLessThanOrEqual(10 * 60 * 1000 + 100); 
  });
});
